[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

# Redirect all /api/* requests to the bundled Express function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = false 